### ISSUE TITLE
Initial setup with Archiecture

### ISSUE THREAD

**Issue by sufiishq-pk** [sufiishq/web-app#1]
We need to set up the base architecture and then will follow the same pattern. Just to make sure the pattern will support the following points.

- Provide high-level architecture.
- Scalability support when the app will grow.
- Community support.
- Active development.
- Provide abstraction.
- Business logic encapsulation.
- Dependency injection.
- Logic isolation.
- Concurrency
- Support testing components.

### Popular Architecture:

- **Bloc** https://pub.dev/packages/flutter_bloc
- **GetX** https://pub.dev/packages/get
- **Provider** https://pub.dev/packages/provider
- **Riverpod** https://riverpod.dev/
- **MobX** https://pub.dev/packages/mobx

**Comment by sufiishq-pk** [comment]
@farhanfahim  I highly recommend using the [Bloc](https://bloclibrary.dev/#/) pattern as it provides a better abstraction level and separation of concern.

```
‘Bloc makes it easy to separate presentation from business logic, making your code fast, easy to test, and reusable.’ 
Bloc (short for Business Logic Component) has become one of Google’s most recommended packages and given the 
quality of its documentation and undoubted popularity within the Flutter community it’s easy to see why.

By encapsulating your business logic into a new class your logic then becomes much more testable and separated from the UI.
Bloc also ensures that there’s only a single way to change the state within your application.
```

For documentation checkout https://bloclibrary.dev/#/gettingstarted

**Comment by syedowaisali** [comment]
@farhanfahim  I highly recommend using the [Bloc](https://bloclibrary.dev/#/) pattern as it provides a better abstraction level and separation of concern.

```
‘Bloc makes it easy to separate presentation from business logic, making your code fast, 
easy to test, and reusable.’ Bloc (short for Business Logic Component) has become 
one of Google’s most recommended packages and given the quality of its 
documentation and undoubted popularity within the Flutter community it’s easy to see why.

By encapsulating your business logic into a new class your logic then becomes much more 
testable and separated from the UI. Bloc also ensures that there’s only a single way to change 
the state within your application.
```

For documentation checkout https://bloclibrary.dev/#/gettingstarted
